# Generated by Django 4.1.3 on 2022-11-05 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=150)),
                ('creationDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('releaseDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artists.artist')),
            ],
        ),
    ]
