# Generated by Django 4.1.3 on 2022-11-06 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='creationDateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='album',
            name='releaseDateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='released on'),
        ),
    ]
