# Generated by Django 4.1.3 on 2022-11-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
