# Generated by Django 4.1.3 on 2022-11-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Song', max_length=150)),
                ('image', models.ImageField(upload_to='songs/%y/%m/%d')),
                ('audioFile', models.FileField(upload_to='audio<django.db.models.fields.CharField>/%y/%m/%d')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='albums.album')),
            ],
        ),
        migrations.DeleteModel(
            name='A',
        ),
    ]
