# Generated by Django 4.1.3 on 2022-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='numberOfApprovedAlbums',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='artist',
            name='socialLink',
            field=models.URLField(blank=True, max_length=250, verbose_name='social media'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stageName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
