# Generated by Django 4.1.3 on 2022-11-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_numberofapprovedalbums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='numberOfApprovedAlbums',
        ),
    ]
