# Generated by Django 4.1.3 on 2022-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artist_numberofapprovedalbums'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='numberOfApprovedAlbums',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
