# Generated by Django 4.1.3 on 2022-11-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_remove_artist_numberofapprovedalbums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='socialLink',
            field=models.URLField(max_length=250, verbose_name='social media'),
        ),
    ]
