# Generated by Django 4.1.3 on 2022-11-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
