# Generated by Django 4.1.3 on 2022-11-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['stageName']},
        ),
    ]
